### ISSUE TITLE
Unable to end call

### ISSUE THREAD

**Issue by pascalgeusen** [VoIPGRID/vialer-android#4]
After using the numeric keypad during a call of when I have to search something on my phone (calendar etc.) I am no longer able to end the call. It would be very handy when the Vialer call would be visible in the notification screen with a "hangup" icon.

**Comment by 00stefan00** [comment]
When you minimize the call to make use of another app during a call (e.g. Calander) you can get back to it by opening the app from the app overview with the overview button (Usually the 3rd button below your screen).

We are looking into adding notifications aswell to match the native android behaviour of phonecalls.

For the numeric keypad problem. It is not completely clear to me what exact problem you encouter. Do you use the keypad from the Vialer app or the native android keypad ?
