### ISSUE TITLE
No 0 on numeric keypad

### ISSUE THREAD

**Issue by pascalgeusen** [VoIPGRID/vialer-android#5]
When I use Vialer to make a call and I have to enter a number (menu choice or supportcode) there is no 0 on the keypad (see the attached image).

![2017-02-15 10 17 26](https://cloud.githubusercontent.com/assets/20997287/22970017/d6e19290-f370-11e6-9176-af1578b1d311.png)

**Comment by 00stefan00** [comment]
I apologize for not having seen this issue before.

This missing 0-key issue should be fixed in the latest version of Vialer.
