### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by barankaraoguzzz** [VoIPGRID/vialer-android#6]
Hello,
I want to use Vialer app's open source but I can't log in, I don't know how to sign up. And I want to use these codes in my project. How can I import these codes in my project?
Best regards.

**Comment by 00stefan00** [comment]
As mentioned in the Readme file under the prerequisites:

- To be able to use the application you will need an account from one of the VoIPGRID partners

The account from one of the VoIPGRID partners should be used to login.
