### ISSUE TITLE
Large fonts break the characters in dial-screen

### ISSUE THREAD

**Issue by wgroenewold** [VoIPGRID/vialer-android#75]
One of my older colleagues experiences problems with large fonts and the dial screen that looks messed up. See attached screenshot.
![whatsapp image 2019-01-09 at 14 24 16](https://user-images.githubusercontent.com/2804722/50902114-54726880-141a-11e9-87f5-25e785ca1ead.jpeg)

**Comment by jeremynorman89** [comment]
Thank you, this bug has been logged and hope to address it in the next few releases.
